import type {
  BootstrapState,
  CatalogModel,
  InstalledModel,
  VoiceProfile,
} from "./types";

export const fallbackCatalog: CatalogModel[] = [
  {
    model_id: "facebook/wav2vec2-base-960h",
    task: "alignment",
    engine: "alignment",
    install_status: "ready",
    revision: "22aad52d435eb6dbaf354bdad9b0da84ce7d6156",
    tier: "recommended",
    recommended_for_12gb: true,
    languages: ["en"],
    summary: "Revision-linked English word alignment with provisional acoustic path scores.",
    default_sample_rate: 16000,
    source_urls: ["https://huggingface.co/facebook/wav2vec2-base-960h"],
  },
  {
    model_id: "microsoft/wavlm-base-plus-sv",
    task: "speaker-verification",
    engine: "speaker-verification",
    install_status: "ready",
    revision: "feb593a6c23c1cc3d9510425c29b0a14d2b07b1e",
    tier: "recommended",
    recommended_for_12gb: true,
    languages: ["en"],
    summary: "Local WavLM x-vector speaker similarity measurement.",
    default_sample_rate: 16000,
    source_urls: ["https://huggingface.co/microsoft/wavlm-base-plus-sv"],
  },
  {
    model_id: "hexgrad/Kokoro-82M",
    task: "tts",
    engine: "kokoro",
    install_status: "ready",
    tier: "recommended",
    recommended_for_12gb: true,
    languages: ["en", "en-gb", "ja", "zh", "ko", "fr", "es", "hi"],
    summary: "Lightweight 82M speech model with low-latency synthesis and 54 voices.",
    default_sample_rate: 24000,
    source_urls: ["https://huggingface.co/hexgrad/Kokoro-82M"],
  },
  {
    model_id: "ResembleAI/chatterbox",
    task: "tts",
    engine: "chatterbox",
    install_status: "ready",
    tier: "recommended",
    recommended_for_12gb: true,
    languages: ["en"],
    summary: "Expressive local synthesis with zero-shot voice cloning.",
    default_sample_rate: 24000,
    source_urls: ["https://huggingface.co/ResembleAI/chatterbox"],
  },
  {
    model_id: "ResembleAI/chatterbox-turbo",
    task: "tts",
    engine: "chatterbox-turbo",
    install_status: "ready",
    tier: "recommended",
    recommended_for_12gb: true,
    languages: ["en"],
    summary: "Lower-latency 350M English synthesis with voice cloning and paralinguistic tags.",
    default_sample_rate: 24000,
    revision: "749d1c1a46eb10492095d68fbcf55691ccf137cd",
    source_urls: ["https://huggingface.co/ResembleAI/chatterbox-turbo"],
  },
  {
    model_id: "coqui/XTTS-v2",
    task: "tts",
    engine: "coqui",
    install_status: "ready",
    tier: "recommended",
    recommended_for_12gb: true,
    languages: ["en", "es", "fr", "de", "it", "pt", "ar", "zh-cn", "ja", "ko"],
    summary: "Multilingual voice cloning with 17-language synthesis.",
    default_sample_rate: 24000,
    source_urls: ["https://huggingface.co/coqui/XTTS-v2"],
  },
  {
    model_id: "microsoft/speecht5_tts",
    task: "tts",
    engine: "speecht5",
    install_status: "planned",
    tier: "smoke",
    recommended_for_12gb: true,
    languages: ["en"],
    summary: "Compact baseline model for validating local synthesis.",
    default_sample_rate: 16000,
    source_urls: ["https://huggingface.co/microsoft/speecht5_tts"],
  },
  {
    model_id: "BreezeBlue/Breeze-TTS-2",
    task: "tts",
    engine: "breeze",
    install_status: "ready",
    revision: "c1c8ca18b70b30822735633991d9ebf4898e47d4",
    tier: "advanced",
    recommended_for_12gb: true,
    languages: ["en", "zh"],
    license: "BreezeBlue Research and Non-Commercial License 1.0",
    summary: "Bilingual 3.47B voice-design model with expressive events and 24 kHz output.",
    default_sample_rate: 24000,
    source_urls: ["https://huggingface.co/BreezeBlue/Breeze-TTS-2"],
  },
  {
    model_id: "fishaudio/fish-speech-1.5",
    task: "tts",
    engine: "fish-speech",
    install_status: "ready",
    revision: "275a984d33c33659e39eed41ff5bcd6e67517f4c",
    tier: "recommended",
    recommended_for_12gb: true,
    languages: ["en", "zh", "ja", "de", "fr", "es", "ko", "ar", "ru", "nl", "it", "pl", "pt"],
    license: "CC-BY-NC-SA-4.0",
    summary: "Stable multilingual Fish Audio synthesis with 44.1 kHz output.",
    default_sample_rate: 44100,
    source_urls: ["https://huggingface.co/fishaudio/fish-speech-1.5"],
  },
  {
    model_id: "openai/whisper-tiny",
    task: "stt",
    engine: "transformers",
    install_status: "ready",
    tier: "smoke",
    recommended_for_12gb: true,
    languages: ["multilingual"],
    summary: "Fast local transcription smoke-test model.",
    default_sample_rate: 16000,
    source_urls: ["https://huggingface.co/openai/whisper-tiny"],
  },
  {
    model_id: "nvidia/parakeet-tdt-1.1b",
    task: "stt",
    engine: "nemo",
    install_status: "planned",
    tier: "recommended",
    recommended_for_12gb: true,
    languages: ["en"],
    summary: "FastConformer-TDT English transcription model.",
    default_sample_rate: 16000,
    source_urls: ["https://huggingface.co/nvidia/parakeet-tdt-1.1b"],
  },
  {
    model_id: "facebook/musicgen-small",
    task: "music",
    engine: "musicgen",
    install_status: "ready",
    revision: "47e682ccac550edc80b042ca977074aee86306e7",
    tier: "recommended",
    recommended_for_12gb: true,
    languages: [],
    license: "CC-BY-NC-4.0",
    summary: "Local text-to-music drafts, rendered at 32 kHz with a 30-second safety cap.",
    default_sample_rate: 32000,
    source_urls: ["https://huggingface.co/facebook/musicgen-small"],
  },
  {
    model_id: "ACE-Step/Ace-Step1.5",
    task: "music",
    engine: "acestep",
    install_status: "ready",
    revision: "19671f406d603126926c1b7e2adc169acbcade22",
    tier: "recommended",
    recommended_for_12gb: true,
    languages: ["en", "zh", "ja", "ko", "es", "fr", "de", "it", "pt", "ru", "ar", "hi"],
    license: "MIT (ACE-Step); Apache-2.0 (Qwen3 text encoder)",
    summary: "ACE-Step Studio with the 2B Turbo song model and 1.7B local planner for complete songs on 12 GB GPUs.",
    default_sample_rate: 48000,
    source_urls: ["https://huggingface.co/ACE-Step/Ace-Step1.5"],
  },
  {
    model_id: "ACE-Step/acestep-v15-base",
    task: "music",
    engine: "acestep",
    install_status: "ready",
    revision: "e432212fec32b8965a14ffa57ae653438d6abd14",
    tier: "advanced",
    recommended_for_12gb: false,
    languages: ["en", "zh", "ja", "ko", "es", "fr", "de", "it", "pt", "ru", "ar", "hi"],
    license: "MIT",
    summary: "ACE-Step Base Tools for stem separation, layer generation, and deeper audio edits.",
    default_sample_rate: 48000,
    source_urls: ["https://huggingface.co/ACE-Step/acestep-v15-base"],
  },
  {
    model_id: "ACE-Step/acestep-v15-xl-turbo-diffusers",
    task: "music",
    engine: "acestep",
    install_status: "ready",
    revision: "200ba991ae448051e14b0183157e35c2d27c9fb0",
    tier: "advanced",
    recommended_for_12gb: false,
    languages: ["en", "es", "fr", "de", "it", "pt", "ja", "ko", "zh", "ru"],
    license: "MIT (ACE-Step); Apache-2.0 (Qwen3 text encoder)",
    summary: "Lyric-conditioned local music at 48 kHz stereo with separate direction and lyrics inputs.",
    default_sample_rate: 48000,
    source_urls: ["https://huggingface.co/ACE-Step/acestep-v15-xl-turbo-diffusers"],
  },
];

const installedIds = new Set([
  "facebook/wav2vec2-base-960h",
  "microsoft/wavlm-base-plus-sv",
  "hexgrad/Kokoro-82M",
  "ResembleAI/chatterbox",
  "coqui/XTTS-v2",
  "microsoft/speecht5_tts",
  "openai/whisper-tiny",
  "nvidia/parakeet-tdt-1.1b",
  "BreezeBlue/Breeze-TTS-2",
  "fishaudio/fish-speech-1.5",
  "facebook/musicgen-small",
  "ACE-Step/Ace-Step1.5",
  "ACE-Step/acestep-v15-base",
  "ACE-Step/acestep-v15-xl-turbo-diffusers",
]);

export const fallbackInstalled: InstalledModel[] = fallbackCatalog
  .filter((model) => installedIds.has(model.model_id))
  .map((model) => ({
    model_id: model.model_id,
    task: model.task,
    engine: model.engine,
    tier: model.tier,
    local_path: `~/.soundAr/models/${model.model_id.replace("/", "__")}`,
    downloaded_at: "2026-03-30T17:05:09Z",
    languages: model.languages,
    license: model.license,
    integrity: { state: "ready", reason: "verified", missing_files: [], invalid_files: [], checked_files: 2, installed_size_bytes: 0, manifest_verified: false },
  }));

const previewReferenceAudio = "data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQAAAAA=";

export const seedVoices: VoiceProfile[] = [
  {
    id: "mara",
    name: "Mara",
    style: "Warm documentary",
    sample_label: "Owner-recorded sample",
    sample_seconds: 18,
    engines: ["Kokoro", "Chatterbox"],
    consent: "confirmed",
    state: "ready",
    color: "green",
    local_path: previewReferenceAudio,
    source_kind: "recorded",
    references: [{
      id: "mara-reference-1",
      original_path: previewReferenceAudio,
      processed_path: previewReferenceAudio,
      original_sha256: "browser-preview-original",
      processed_sha256: "browser-preview-processed",
      analysis: {
        duration_seconds: 18,
        sample_rate: 24_000,
        channels: 1,
        peak_dbfs: -1,
        silence_ratio: 0.04,
        clipping_ratio: 0,
        waveform: Array.from({ length: 72 }, (_, index) => 0.16 + Math.abs(Math.sin(index * 0.41)) * 0.74),
      },
      processing: {
        schema_version: 2,
        selection_start_seconds: 0.2,
        selection_end_seconds: 17.8,
        remove_silence: true,
        normalize: true,
      },
      active: true,
      created_at: "2026-08-12T12:00:00Z",
      transcript_text: "The best voices feel present before they sound perfect.",
      transcript_source: "corrected",
      revision_count: 1,
    }],
  },
  {
    id: "amara",
    name: "Amara",
    style: "Clear narration",
    sample_label: "Verified local sample",
    sample_seconds: 31,
    engines: ["Kokoro", "XTTS"],
    consent: "confirmed",
    state: "ready",
    color: "green",
  },
  {
    id: "studio-neutral",
    name: "Studio Neutral",
    style: "Utility preset",
    sample_label: "Built-in voice",
    sample_seconds: 0,
    engines: ["Kokoro"],
    consent: "not-required",
    state: "preset",
    color: "amber",
  },
  {
    id: "oyin-test",
    name: "Oyin — test",
    style: "Conversational",
    sample_label: "Sample needs review",
    sample_seconds: 12,
    engines: ["Chatterbox"],
    consent: "pending",
    state: "draft",
    color: "coral",
  },
];

export const fallbackBootstrap: BootstrapState = {
  catalog: fallbackCatalog,
  installed: fallbackInstalled,
  system: {
    gpu_name: "NVIDIA GeForce RTX 4080 Laptop GPU",
    vram_total_mb: 12282,
    vram_used_mb: 1265,
    driver_version: "595.84",
    cuda_available: true,
    python_ready: true,
  },
  scheduler: {
    active_workers: 0,
    max_workers: 4,
    engine_limits: { "fish-speech": 1 },
    reserved_vram_mb: 0,
    available_vram_budget_mb: 11017,
    active_batches: 0,
  },
  export_dir: "~/.soundAr/exports",
  voices: seedVoices,
  jobs: [],
  presets: [],
  projects: [{
    id: "preview-project",
    name: "Local AI, Close to Home",
    document: {
      script: "A finished two-voice conversation about practical local AI.",
      speaker_assignments: {},
      chapters: [
        { id: "preview-chapter-1", title: "Opening", text: "Local AI keeps useful tools close to home.", language: "en", history_id: "preview-take-1" },
        { id: "preview-chapter-2", title: "Closing", text: "The result stays available even when the network does not.", language: "en", history_id: "preview-take-2" },
      ],
      master: {
        history_id: "preview-project-master",
        audio_path: previewReferenceAudio,
        title: "Local AI, Close to Home · Full Dialogue",
        duration_seconds: 113.88,
        sample_rate: 24000,
        format: "wav",
        created_at: "2026-08-27T18:03:00Z",
      },
    },
    created_at: "2026-08-27T17:41:00Z",
    updated_at: "2026-08-27T18:03:00Z",
  }],
  transcriptions: [{
    id: "preview-transcript", job_id: "preview-transcription-job", source_path: previewReferenceAudio,
    original_source_path: previewReferenceAudio, model_id: "openai/whisper-tiny", engine: "transformers",
    text: "Sound our local API GPU test.", original_text: "Sound our local API GPU test.",
    segments: [{ text: "Sound our local API GPU test.", start_seconds: 0.26, end_seconds: 3.075 }],
    words: [
      { text: "Sound", start_seconds: 0.26, end_seconds: 0.6 },
      { text: "our", start_seconds: 0.6, end_seconds: 0.8 },
      { text: "local", start_seconds: 0.8, end_seconds: 1.1 },
      { text: "API", start_seconds: 1.1, end_seconds: 1.6 },
      { text: "GPU", start_seconds: 1.6, end_seconds: 2.22 },
      { text: "test.", start_seconds: 2.22, end_seconds: 3.075, end_inferred: true },
    ],
    detected_language: "en", language_confidence: 0.9956,
    evidence: { schema_version: 1, timing_source: "whisper-token-alignment", language_source: "whisper-decoder-logits", word_confidence_source: "unavailable" },
    diarization: {
      id: "preview-diarization", job_id: "preview-diarization-job", model_id: "microsoft/wavlm-base-plus-sv", engine: "speaker-verification",
      speakers: [{ id: "speaker-1", default_name: "Speaker 1" }, { id: "speaker-2", default_name: "Speaker 2" }],
      turns: [
        { speaker_id: "speaker-1", start_seconds: 0.26, end_seconds: 1.1, word_start_index: 0, word_end_index: 2, text: "Sound our local", confidence: null },
        { speaker_id: "speaker-2", start_seconds: 1.1, end_seconds: 3.075, word_start_index: 3, word_end_index: 5, text: "API GPU test.", confidence: null },
      ],
      evidence: { schema_version: 1, method: "wavlm-xvector-word-window-clustering", clustering: "average-link-cosine", distance_threshold: 0.32, speaker_count_mode: "automatic", requested_speaker_count: null, speech_window_count: 2, overlap_detection: false, confidence_source: "unavailable", provisional: true },
      inference_seconds: 0.24, vram_peak_mb: 620,
      labels: { "speaker-1": "Speaker 1", "speaker-2": "Speaker 2" }, label_revision_count: 0, labels_updated_at: null,
      created_at: "2026-08-13T00:00:00Z",
    },
    alignment: {
      id: "preview-alignment", job_id: "preview-alignment-job", model_id: "facebook/wav2vec2-base-960h", engine: "alignment",
      source_revision: 0, source_text_sha256: "browser-preview", current: true,
      words: [
        { text: "Sound", start_seconds: 0.26, end_seconds: 0.6, alignment_score: 0.92, segment_index: 0 },
        { text: "our", start_seconds: 0.6, end_seconds: 0.8, alignment_score: 0.89, segment_index: 0 },
        { text: "local", start_seconds: 0.8, end_seconds: 1.1, alignment_score: 0.9, segment_index: 0 },
        { text: "API", start_seconds: 1.1, end_seconds: 1.6, alignment_score: 0.83, segment_index: 0 },
        { text: "GPU", start_seconds: 1.6, end_seconds: 2.22, alignment_score: 0.86, segment_index: 0 },
        { text: "test", start_seconds: 2.22, end_seconds: 3.075, alignment_score: 0.88, segment_index: 0 },
      ],
      evidence: { schema_version: 1, method: "browser-preview", language: "en", source_revision_linked: true, score_source: "preview-only", score_calibrated: false, original_timestamps_preserved: true, provisional: true },
      mean_alignment_score: 0.88, inference_seconds: 0.18, vram_peak_mb: 512, created_at: "2026-08-13T00:00:00Z",
    },
    processing: { schema_version: 1, algorithm: "none" }, audio_duration_seconds: 3.075,
    inference_seconds: 0.34, rtf: 0.04, vram_peak_mb: 700, revision_count: 0,
    created_at: "2026-08-13T00:00:00Z", updated_at: "2026-08-13T00:00:00Z",
  }],
  benchmarks: [],
  batches: [],
  comparisons: [],
  settings: { theme: "light", dense_tables: true, reduced_motion: false },
  features: {
    generate: "stable",
    projects: "beta",
    models: "beta",
    voices: "beta",
    history: "beta",
    compare: "experimental",
    benchmarks: "experimental",
    live: "beta",
    transcribe: "beta",
    developer_api: "beta",
  },
  engine_capabilities: [
    { id: "alignment", display_name: "Wav2Vec2 Forced Alignment", adapter_version: 1, tasks: ["alignment"], languages: ["en"], voice_modes: [], streaming: false, reference_formats: ["wav", "flac", "mp3", "m4a", "ogg"], output_formats: [], controls: {}, alignment_evidence: { word_timestamps: true, acoustic_path_score: true, score_calibrated: false, source_revision_linked: true, provisional: true }, minimum_vram_mb: 1400, license: "Apache-2.0" },
    { id: "speaker-verification", display_name: "WavLM Speaker Verification", adapter_version: 2, tasks: ["speaker-verification", "speaker-diarization"], languages: ["en"], voice_modes: ["reference"], streaming: false, reference_formats: ["wav", "flac", "mp3", "m4a", "ogg"], output_formats: [], controls: {}, diarization_evidence: { word_anchored: true, editable_labels: true, overlap_detection: false, turn_confidence: false, provisional: true }, minimum_vram_mb: 1800, license: "CC-BY-SA-3.0" },
    { id: "kokoro", display_name: "Kokoro", adapter_version: 1, tasks: ["tts"], languages: ["en", "en-gb", "ja", "zh", "ko", "fr", "es", "hi", "it", "pt"], voice_modes: ["preset"], streaming: false, reference_formats: [], output_formats: ["wav", "flac"], controls: { speed: { type: "number", minimum: 0.7, maximum: 1.3, default: 1 } }, minimum_vram_mb: 768, license: "Apache-2.0" },
    { id: "transformers", display_name: "Whisper", adapter_version: 2, tasks: ["stt"], languages: ["multilingual"], voice_modes: [], streaming: false, reference_formats: ["wav", "flac", "mp3", "m4a", "ogg"], output_formats: [], controls: {}, transcription_evidence: { word_timestamps: true, language_detection: true, declared_language: false, word_confidence: false }, minimum_vram_mb: 512, license: "MIT" },
    { id: "speecht5", display_name: "SpeechT5", adapter_version: 1, tasks: ["tts"], languages: ["en"], voice_modes: ["default"], streaming: false, reference_formats: [], output_formats: ["wav", "flac"], controls: {}, minimum_vram_mb: 1800, license: "MIT" },
    { id: "chatterbox", display_name: "Chatterbox", adapter_version: 1, tasks: ["tts", "voice-clone"], languages: ["en"], voice_modes: ["default", "reference"], streaming: false, reference_formats: ["wav", "flac", "mp3", "m4a", "ogg"], output_formats: ["wav", "flac"], controls: { exaggeration: { type: "number", minimum: 0, maximum: 1, default: 0.5 }, cfg_weight: { type: "number", minimum: 0, maximum: 1, default: 0.5 } }, minimum_vram_mb: 7000, license: "MIT" },
    { id: "chatterbox-turbo", display_name: "Chatterbox Turbo", adapter_version: 1, tasks: ["tts", "voice-clone"], languages: ["en"], voice_modes: ["default", "reference"], streaming: false, reference_formats: ["wav", "flac", "mp3", "m4a", "ogg"], output_formats: ["wav", "flac"], controls: { temperature: { type: "number", minimum: 0.1, maximum: 2, default: 0.8 }, top_p: { type: "number", minimum: 0.1, maximum: 1, default: 0.95 }, repetition_penalty: { type: "number", minimum: 1, maximum: 2, default: 1.2 } }, minimum_vram_mb: 5000, license: "MIT" },
    { id: "breeze", display_name: "Breeze TTS 2", adapter_version: 1, tasks: ["tts"], languages: ["en", "zh"], voice_modes: ["default"], streaming: false, reference_formats: [], output_formats: ["wav", "flac"], controls: { cfg_scale: { type: "number", minimum: 1, maximum: 4, default: 1 } }, minimum_vram_mb: 7885, license: "BreezeBlue Research and Non-Commercial License 1.0" },
    { id: "fish-speech", display_name: "Fish Speech 1.5", adapter_version: 1, tasks: ["tts"], languages: ["en", "zh", "ja", "de", "fr", "es", "ko", "ar", "ru", "nl", "it", "pl", "pt"], voice_modes: ["default"], streaming: false, reference_formats: [], output_formats: ["wav", "flac"], controls: { temperature: { type: "number", minimum: 0.1, maximum: 1, default: 0.7 }, top_p: { type: "number", minimum: 0.1, maximum: 1, default: 0.7 }, repetition_penalty: { type: "number", minimum: 0.9, maximum: 2, default: 1.2 } }, minimum_vram_mb: 6144, license: "CC-BY-NC-SA-4.0" },
    { id: "coqui", display_name: "XTTS v2", adapter_version: 1, tasks: ["tts", "voice-clone"], languages: ["en", "es", "fr", "de", "it", "pt", "pl", "tr", "ru", "nl", "cs", "ar", "zh-cn", "ja", "hu", "ko", "hi"], voice_modes: ["reference"], streaming: false, reference_formats: ["wav", "flac", "mp3", "m4a", "ogg"], output_formats: ["wav", "flac"], controls: { speed: { type: "number", minimum: 0.7, maximum: 1.3, default: 1 } }, minimum_vram_mb: 10800, license: "CPML" },
    { id: "nemo", display_name: "NVIDIA NeMo", adapter_version: 2, tasks: ["stt"], languages: ["en"], voice_modes: [], streaming: false, reference_formats: ["wav", "flac", "mp3", "m4a", "ogg"], output_formats: [], controls: {}, transcription_evidence: { word_timestamps: true, language_detection: false, declared_language: true, word_confidence: true }, minimum_vram_mb: 8600, license: "Apache-2.0" },
    { id: "musicgen", display_name: "MusicGen", adapter_version: 1, tasks: ["music"], languages: [], voice_modes: [], streaming: false, reference_formats: [], output_formats: ["wav", "flac"], controls: { duration_seconds: { type: "number", minimum: 4, maximum: 30, default: 10 }, guidance_scale: { type: "number", minimum: 1, maximum: 6, default: 3 }, temperature: { type: "number", minimum: 0.1, maximum: 2, default: 1 }, top_k: { type: "number", minimum: 0, maximum: 250, default: 250 }, top_p: { type: "number", minimum: 0, maximum: 1, default: 0 } }, music_features: { lyrics: false, instrumental_when_lyrics_empty: true, sample_rate: 32000, channels: 1 }, minimum_vram_mb: 6144, license: "CC-BY-NC-4.0" },
    { id: "acestep", display_name: "ACE-Step 1.5 Studio", adapter_version: 2, tasks: ["music"], languages: ["en", "zh", "ja", "ko", "es", "fr", "de", "it", "pt", "ru", "ar", "hi"], voice_modes: [], streaming: false, reference_formats: ["wav", "flac", "mp3", "m4a", "ogg"], output_formats: ["wav", "flac"], controls: { duration_seconds: { type: "number", minimum: 10, maximum: 600, default: 90 }, inference_steps: { type: "number", minimum: 1, maximum: 200, default: 8 }, shift: { type: "number", minimum: 1, maximum: 5, default: 3 }, bpm: { type: "number", minimum: 0, maximum: 300, default: 0 }, audio_cover_strength: { type: "number", minimum: 0, maximum: 1, default: 0.5 }, repainting_start: { type: "number", minimum: 0, maximum: 600, default: 0 }, repainting_end: { type: "number", minimum: -1, maximum: 600, default: -1 } }, music_features: { lyrics: true, instrumental_when_lyrics_empty: true, planner: true, reference_audio: true, cover: true, repaint: true, extend: true, lyric_timing: true, stems: true, max_variations: 8, max_duration_seconds: 600, max_lyrics_characters: 4096, max_lyrics_characters_per_second: 36, sample_rate: 48000, channels: 2 }, minimum_vram_mb: 4096, license: "MIT" },
  ],
  engine_runtimes: [
    { engine: "alignment", state: "legacy-shared", python_path: "~/.local/share/soundar/runtime/.venv/bin/python", runtime_manifest: {}, warm_workers: 0, loaded_models: [] },
    { engine: "speaker-verification", state: "legacy-shared", python_path: "~/.local/share/soundar/runtime/.venv/bin/python", runtime_manifest: {}, warm_workers: 0, loaded_models: [] },
    { engine: "kokoro", state: "legacy-shared", python_path: "~/.local/share/soundar/runtime/.venv/bin/python", runtime_manifest: {}, warm_workers: 0, loaded_models: [] },
    { engine: "transformers", state: "legacy-shared", python_path: "~/.local/share/soundar/runtime/.venv/bin/python", runtime_manifest: {}, warm_workers: 0, loaded_models: [] },
    { engine: "speecht5", state: "legacy-shared", python_path: "~/.local/share/soundar/runtime/.venv/bin/python", runtime_manifest: {}, warm_workers: 0, loaded_models: [] },
    { engine: "chatterbox", state: "legacy-shared", python_path: "~/.local/share/soundar/runtime/.venv/bin/python", runtime_manifest: {}, warm_workers: 0, loaded_models: [] },
    { engine: "chatterbox-turbo", state: "legacy-shared", python_path: "~/.local/share/soundar/runtime/.venv/bin/python", runtime_manifest: {}, warm_workers: 0, loaded_models: [] },
    { engine: "breeze", state: "legacy-shared", python_path: "~/.local/share/soundar/runtime/.venv/bin/python", runtime_manifest: {}, warm_workers: 0, loaded_models: [] },
    { engine: "fish-speech", state: "legacy-shared", python_path: "~/.local/share/soundar/runtime/.venv/bin/python", runtime_manifest: {}, warm_workers: 0, loaded_models: [] },
    { engine: "coqui", state: "legacy-shared", python_path: "~/.local/share/soundar/runtime/.venv/bin/python", runtime_manifest: {}, warm_workers: 0, loaded_models: [] },
    { engine: "nemo", state: "legacy-shared", python_path: "~/.local/share/soundar/runtime/.venv/bin/python", runtime_manifest: {}, warm_workers: 0, loaded_models: [] },
    { engine: "musicgen", state: "legacy-shared", python_path: "~/.local/share/soundar/runtime/.venv/bin/python", runtime_manifest: {}, warm_workers: 0, loaded_models: [] },
    { engine: "acestep", state: "legacy-shared", python_path: "~/.local/share/soundar/runtime/.venv/bin/python", runtime_manifest: {}, warm_workers: 0, loaded_models: [] },
  ],
  install_kind: "development",
  runtime: "browser",
};
